# Generated by Django 3.0.4 on 2020-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200328_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field='40', upload_to='images/'),
        ),
    ]
